version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend-tooling:
        patterns: ['*']

  - package-ecosystem: terraform
    directory: /infra/bootstrap
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/site
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
